package test.dao;

import java.util.List;
import test.modal.SysUserPrivilege;

public interface SysUserPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_privilege
     *
     * @mbg.generated
     */
    int insert(SysUserPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_privilege
     *
     * @mbg.generated
     */
    List<SysUserPrivilege> selectAll();
}